# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 625b2df51849be67b8257d3247b5546d99f2bf823d36c5f1038f5cf1cb00f6e2cd549644ba5560d6096a86d7dc6477e7731cb076f805945b9f322d46fd0f168f

test:
  secret_key_base: 5496e4d59801c7a70a3fa103780e193fd07146a409cd94e364aea5c82e5dea20987d0c8463ba1c88b95cb498f4b19261243063cbc4864dff1f08ca215ad57d94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
